name: dhbwstudentapp
description: An app for the DHBW Stuttgart

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  app_group_directory: ^2.0.0
  copy_with_extension: ^4.0.0
  device_calendar: ^4.2.0
  equatable: ^2.0.0
  firebase_analytics: ^9.1.6
  firebase_core: ^1.15.0
  firebase_crashlytics: ^2.6.3 # BREAKING CHANGES: iOS Min Plaform has to be updated
  flutter:
    sdk: flutter
  flutter_inapp_purchase: ^5.1.2
  flutter_local_notifications: ^9.4.1 # BREAKING CHANGES HERE!
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_secure_storage: ^5.0.2
  flutter_widgetkit: ^1.0.3
  html: ^0.15.0
  http: ^0.13.4
  http_client_helper: ^2.0.2
  intl: ^0.17.0
  json_annotation: ^4.7.0
  kiwi: ^4.0.2
  launch_review: ^3.0.1
  mutex: ^3.0.0
  path: ^1.8.0
  path_provider: ^2.0.9
  property_change_notifier: ^0.3.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2+1
  timezone: ^0.8.0
  universal_html: ^2.0.8
  url_launcher: ^6.1.0
  workmanager: ^0.5.0

dev_dependencies:
  assets_gen: ^1.2.0
  build_runner: ^2.3.0
  copy_with_extension_gen: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.0
  lint: ^1.10.0

  test: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/empty_state.png
    - assets/app_icon.png
    - assets/splash.png
    - assets/onboarding_bottom_background.png
    - assets/onboarding_bottom_foreground.png
    - assets/onboarding_bottom_background_dark.png
    - assets/onboarding_bottom_foreground_dark.png
    - assets/schedule_empty_state.png
    - assets/schedule_empty_state_dark.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
