// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 9.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'dhbwstudentapp';

  static const String assets_app_icon_png = 'assets/app_icon.png';
  static const String dhbwstudentapp$assets_app_icon_png = 'packages/dhbwstudentapp/assets/app_icon.png';

  static const String assets_empty_state_png = 'assets/empty_state.png';
  static const String dhbwstudentapp$assets_empty_state_png = 'packages/dhbwstudentapp/assets/empty_state.png';

  static const String assets_onboarding_bottom_background_png = 'assets/onboarding_bottom_background.png';
  static const String dhbwstudentapp$assets_onboarding_bottom_background_png = 'packages/dhbwstudentapp/assets/onboarding_bottom_background.png';

  static const String assets_onboarding_bottom_background_dark_png = 'assets/onboarding_bottom_background_dark.png';
  static const String dhbwstudentapp$assets_onboarding_bottom_background_dark_png = 'packages/dhbwstudentapp/assets/onboarding_bottom_background_dark.png';

  static const String assets_onboarding_bottom_foreground_png = 'assets/onboarding_bottom_foreground.png';
  static const String dhbwstudentapp$assets_onboarding_bottom_foreground_png = 'packages/dhbwstudentapp/assets/onboarding_bottom_foreground.png';

  static const String assets_onboarding_bottom_foreground_dark_png = 'assets/onboarding_bottom_foreground_dark.png';
  static const String dhbwstudentapp$assets_onboarding_bottom_foreground_dark_png = 'packages/dhbwstudentapp/assets/onboarding_bottom_foreground_dark.png';

  static const String assets_schedule_empty_state_png = 'assets/schedule_empty_state.png';
  static const String dhbwstudentapp$assets_schedule_empty_state_png = 'packages/dhbwstudentapp/assets/schedule_empty_state.png';

  static const String assets_schedule_empty_state_dark_png = 'assets/schedule_empty_state_dark.png';
  static const String dhbwstudentapp$assets_schedule_empty_state_dark_png = 'packages/dhbwstudentapp/assets/schedule_empty_state_dark.png';

  static const String assets_splash_png = 'assets/splash.png';
  static const String dhbwstudentapp$assets_splash_png = 'packages/dhbwstudentapp/assets/splash.png';
}
